file-version: 1
permissions:
  message: "privatemessages.message"
  reply: "privatemessages.reply"
last_message_reply: false
messages:
  # Supports MiniMessages Formatting https://docs.advntr.dev/minimessage/format.html
  # For receiver name use <receiver>
  # For sender name use <sender>
  # For the message use <message>
  message_usage: "Please use /message <player> <message>."
  message_self: "You cannot send messages to yourself."
  message_first: "To use this command, you need to first talk to another player using /message <player> <message>"
  reply_usage: "Please use /reply <message>."
  player_not_found: "The player <receiver> is not online."
  player_disconnect: "The player you were talking to is no longer online."
format:
  sender: "You -> <receiver>: <message>"
  receiver: "<sender> -> You: <message>"
